spring:
  datasource:
    url: jdbc:mysql://localhost:3306/db_access
    username: user_access
    password: access
  jpa:
    show_sql: true
    hibernate:
      ddl-auto: none

server:
  port: 8888
  servlet:
    context-path: /sec
